### ISSUE TITLE
speculative execution in cluster mode single leads to panic

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1001]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6decf6]

goroutine 47653 [running]:
net/http.(*Transport).cancelRequest(0x0, 0xcae7d67000, 0xfca2a0, 0xc4200beaa0)
        /usr/local/go/src/net/http/transport.go:564 +0x26
net/http.(*Transport).CancelRequest(0x0, 0xcae7d67000)
        /usr/local/go/src/net/http/transport.go:559 +0x4d
github.com/grafana/metrictank/cluster.HTTPNode.Post(0xc4201d7e8b, 0xc, 0xfc91e0, 0x12, 0x1, 0xbed5247ff86fb531, 0x852982, 0x15204e0, 0x1, 0x0, ...)
        /go/src/github.com/grafana/metrictank/cluster/node.go:181 +0xb73
github.com/grafana/metrictank/api.(*Server).peerQuerySpeculative.func1(0xc400000000, 0xfdc880, 0xc4215557a0)
        /go/src/github.com/grafana/metrictank/api/cluster.go:336 +0x243
created by github.com/grafana/metrictank/api.(*Server).peerQuerySpeculative
        /go/src/github.com/grafana/metrictank/api/cluster.go:359 +0x4f8
```

note the `0x0` pointer. HTTPNode.Post calls `transport.CancelRequest(req)` on a `nil` transport

**Comment by Dieterbe** [comment]
this is an effect caused by the speculative execution feature using clustering at all times and doing Post requests to all nodes, including itself.
possible solutions:
1) #1000 : enable the http transport for cluster=single. downsides: a bit weird, but less so than the weirdness we already have (using network requests to self)
2) refactor the code to use the local path to itself. this is something we want to do anyway, but it'll take a bit longer to implement.
