### ISSUE TITLE
NotifierKafka nilpointer at startup

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1260]
```
2019-03-28 15:56:42.205 [INFO] kafka-cluster: consuming from p-58844-L-foo:65 from offset -2
[Macaron] 2019-03-28 15:56:42: Started GET /node for 10.36.56.1
[Macaron] 2019-03-28 15:56:42: Completed /node 200 OK in 875.887µs
2019/03/28 15:56:43 [DEBUG] memberlist: Stream connection from=10.36.55.18:41370
2019/03/28 15:56:44 [DEBUG] memberlist: Initiating push/pull sync with: 10.36.51.29:7946
[Macaron] 2019-03-28 15:56:46: Started GET /prometheus/metrics for 10.36.12.18
[Macaron] 2019-03-28 15:56:46: Completed /prometheus/metrics 200 OK in 2.485648ms
[Macaron] 2019-03-28 15:56:50: Started GET / for 10.36.56.1
[Macaron] 2019-03-28 15:56:50: Completed / 503 Service Unavailable in 803.096µs
[Macaron] 2019-03-28 15:56:52: Started GET /node for 10.36.56.1
[Macaron] 2019-03-28 15:56:52: Completed /node 200 OK in 915.435µs
[Macaron] 2019-03-28 15:57:00: Started GET / for 10.36.56.1
[Macaron] 2019-03-28 15:57:00: Completed / 503 Service Unavailable in 728.882µs
[Macaron] 2019-03-28 15:57:01: Started GET /prometheus/metrics for 10.36.12.18
[Macaron] 2019-03-28 15:57:01: Completed /prometheus/metrics 200 OK in 6.374403ms
[Macaron] 2019-03-28 15:57:02: Started GET /node for 10.36.56.1
[Macaron] 2019-03-28 15:57:02: Completed /node 200 OK in 2.438481ms
[Sarama] 2019/03/28 15:57:02 kafka: error while consuming p-58844-L-foo/69: kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.
[Sarama] 2019/03/28 15:57:02 consumer/p-58844-L-foo/69 shutting down because kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd0708a]

goroutine 11664336 [running]:
github.com/grafana/metrictank/mdata/notifierKafka.(*NotifierKafka).consumePartition(0xc1fca9a640, 0xc0000483a7, 0x13, 0x45, 0xfffffffffffffffe, 0xc1af9ab674)
        /go/src/github.com/grafana/metrictank/mdata/notifierKafka/notifierKafka.go:136 +0x8da
created by github.com/grafana/metrictank/mdata/notifierKafka.(*NotifierKafka).start
        /go/src/github.com/grafana/metrictank/mdata/notifierKafka/notifierKafka.go:92 +0x103
```
```
v0.11.0-150-g707e6ce
```

**Comment by Dieterbe** [comment]
https://github.com/grafana/metrictank/blob/707e6ce7df0c7cd53f73b75a282212f023ae9af8/mdata/notifierKafka/notifierKafka.go#L136

**Comment by Dieterbe** [comment]
seems to be the same as #520 / #748
