### ISSUE TITLE
Memory leak in v0.13.1

### ISSUE THREAD

**Issue by D3luxee** [grafana/metrictank#1933]
**Describe the bug**
Metrictank started to fill up the available memory over a time period of 15 hours at the beginning there was ~180GB memory available.
This happened on both shard nodes that were working on the same partitions, the other shard nodes (different partition set) were not affected by this issue.
Because this affected both shard nodes in the same way and at the same time it looks like it was triggered by something both nodes had to do (metric of death?)

Recently we upgraded the carbon-relay-ng from 0.11.0 to 0.13.0 this changed the partitioner and redistributed the metrics to different shard nodes. This could be related but i think its unlikely because there was so much time (3 days) between the upgrade of carbon-relay-ng and this bug.

The stacktrace below might not be related to the main issue, the memory was filling up from Oct 28 09:00 UTC but the messages below appeared at Oct 29 00:01 UTC and at 00:01 the memory was already full and reached its limits.

**Additional context**
```
 sync.runtime_SemacquireMutex(0xc00030c00c, 0x0, 0x0)
         /usr/lib/go/src/runtime/sema.go:71 +0x47
 sync.(*RWMutex).RLock(...)
         /usr/lib/go/src/sync/rwmutex.go:50
 github.com/grafana/metrictank/mdata/cache.(*CCache).AddIfHot(0xc00030c000, 0x8e05bc108ff81e25, 0x9433f4aeb581bbb0, 0x4, 0x100000000000000, 
         /home/gdoser/go/src/github.com/grafana/metrictank/mdata/cache/ccache.go:122 +0x1b3
 created by github.com/grafana/metrictank/mdata.(*AggMetric).pushToCache
         /home/gdoser/go/src/github.com/grafana/metrictank/mdata/aggmetric.go:352 +0x145
 goroutine 24186934354 [semacquire, 880 minutes]:
 sync.runtime_SemacquireMutex(0xc00030c00c, 0xdbdcea1100, 0x0)
         /usr/lib/go/src/runtime/sema.go:71 +0x47
 sync.(*RWMutex).RLock(...)
         /usr/lib/go/src/sync/rwmutex.go:50
 github.com/grafana/metrictank/mdata/cache.(*CCache).AddIfHot(0xc00030c000, 0xf5debccdc2df98f5, 0x4f661793b2dc3252, 0x4, 0x100000000000000, 
         /home/gdoser/go/src/github.com/grafana/metrictank/mdata/cache/ccache.go:122 +0x1b3
 created by github.com/grafana/metrictank/mdata.(*AggMetric).pushToCache
         /home/gdoser/go/src/github.com/grafana/metrictank/mdata/aggmetric.go:352 +0x145
 goroutine 24186929531 [semacquire, 880 minutes]:
 sync.runtime_SemacquireMutex(0xc00030c00c, 0x0, 0x0)
         /usr/lib/go/src/runtime/sema.go:71 +0x47
 sync.(*RWMutex).RLock(...)
         /usr/lib/go/src/sync/rwmutex.go:50
```

**Helpful Information**
Metrictank Version: v0.13.1
Golang Version (if not using an official binary or docker image): version: go1.14.3
OS: Debian 9
Please also list any other software versions you think would be useful to debug the problem (i.e. Cassandra, Kafka, etc...):

- carbon-relay-ng 0.13.0
- kafka 2.3.0
- cassandra 3.11.3

**Comment by D3luxee** [comment]
Hi @Dieterbe 
i think i can't help here, metrictank went out of memory on both nodes and we had to restart it. Now it is running normally and i guess a profile would not help you at this moment?

The dashboard snapshot would not be helpful either since we send the metrictank metrics into metrictank itself and we lost a 5h time window of metrics yesterday there is not much helpful information left. And i can't share a snapshot since our grafana is only reachable internally and not via the internet.
But i could take some screenshots if you want to.

**Comment by D3luxee** [comment]
Hi @Dieterbe 
i just checked our config again and the profiletrigger-* were already enabled, since one of the affected nodes did not require a reboot i got memory profiles.
I will collect the profiles for the given time period and attach it on this comment.
