### ISSUE TITLE
deadlock in processWriteQueue

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#777]
```
goroutine 796 [select, 2231 minutes]:
github.com/raintank/metrictank/vendor/github.com/gocql/gocql.(*Conn).exec(0xc420a9e000, 0x0, 0x0, 0x1025720, 0xc4345e1f10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/gocql/gocql/conn.go:637 +0x74f
github.com/raintank/metrictank/vendor/github.com/gocql/gocql.(*Conn).executeQuery(0xc420a9e000, 0xc430732200, 0xc407cc7dfe)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/gocql/gocql/conn.go:830 +0x575
github.com/raintank/metrictank/vendor/github.com/gocql/gocql.(*Query).execute(0xc430732200, 0xc420a9e000, 0x1069b20)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/gocql/gocql/session.go:750 +0x35
github.com/raintank/metrictank/vendor/github.com/gocql/gocql.(*queryExecutor).executeQuery(0xc420986180, 0x1033660, 0xc430732200, 0xc42f7a0013, 0x3, 0xc427de7c68)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/gocql/gocql/query_executor.go:42 +0x1b3
github.com/raintank/metrictank/vendor/github.com/gocql/gocql.(*Session).executeQuery(0xc420184280, 0xc430732200, 0xc427de7c00)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/gocql/gocql/session.go:376 +0xc1
github.com/raintank/metrictank/vendor/github.com/gocql/gocql.(*Query).Iter(0xc430732200, 0xc430732200)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/gocql/gocql/session.go:921 +0xbf
github.com/raintank/metrictank/vendor/github.com/gocql/gocql.(*Query).Exec(0xc430732200, 0xc42b09f1d0, 0x45)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/gocql/gocql/session.go:904 +0x2b
github.com/raintank/metrictank/mdata.(*CassandraStore).insertChunk(0xc42089a600, 0xc4240dcf30, 0x26, 0xa8c005a2627d0, 0xc43c631520, 0x4a, 0xc8, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/mdata/store_cassandra.go:370 +0x467
github.com/raintank/metrictank/mdata.(*CassandraStore).processWriteQueue(0xc42089a600, 0xc420a881e0, 0xc420bcc0e0)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/mdata/store_cassandra.go:309 +0x398
created by github.com/raintank/metrictank/mdata.NewCassandraStore
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/mdata/store_cassandra.go:267 +0x1008
```

gocql is getting into a deadlock state.

see also #726

**Comment by woodsaj** [comment]
as mentioned in #726 we need to update gocql to the latest version and also use a context.WithTimeout when making queries.
