### ISSUE TITLE
panic during kafka problem

### ISSUE THREAD

**Issue by motyla** [grafana/metrictank#801]
Hi ,

Seems that Metrictank is getting panic while kafka have issues. We had some issue with Metrictank kafka (it was under replicated and not available at some point) during that our metrictank got panic and restarted itself.
Seems to me this is not the desired behavior taking into account Metrictank is serving metrics (grafana) . below metrictank logs during that time:

```
Dec 25 07:48:43 metrictank metrictank[131940]: [Sarama] 2017/12/25 07:48:43 consumer/broker/1 added subscription to metrics/89
Dec 25 07:48:43 metrictank metrictank[131940]: [Sarama] 2017/12/25 07:48:43 kafka: error while consuming mdm/33: kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.
Dec 25 07:48:43 metrictank metrictank[131940]: [Sarama] 2017/12/25 07:48:43 consumer/mdm/33 shutting down because kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.
Dec 25 07:48:43 metrictank metrictank[131940]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 25 07:48:43 metrictank metrictank[131940]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xad442d]
Dec 25 07:48:43 metrictank metrictank[131940]: goroutine 9446 [running]:
Dec 25 07:48:43 metrictank metrictank[131940]: github.com/grafana/metrictank/input/kafkamdm.(*KafkaMdm).consumePartition(0xc420140000, 0xc42009af2d, 0x6, 0x21, 0x1bb9b615)
Dec 25 07:48:43 metrictank metrictank[131940]: /home/ubuntu/.go_workspace/src/github.com/grafana/metrictank/input/kafkamdm/kafkamdm.go:296 +0x70d
Dec 25 07:48:43 metrictank metrictank[131940]: created by github.com/grafana/metrictank/input/kafkamdm.(*KafkaMdm).Start
Dec 25 07:48:43 metrictank metrictank[131940]: /home/ubuntu/.go_workspace/src/github.com/grafana/metrictank/input/kafkamdm/kafkamdm.go:216 +0xe0
Dec 25 07:48:48 metrictank metrictank[92461]: [Sarama] 2017/12/25 07:48:48 Initializing new client
```

**Comment by Dieterbe** [comment]
it is expected for MT to abort when it cannot get the data from kafka. however, it should emit a better error. see #520
