### ISSUE TITLE
Metrictank crashes when asking for an aggregation that doesn't exist

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#835]
For an aggregation configured to only compute `min` rollups, if a user asks for `avg` metrictank crashes:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x99bab4]
goroutine 344721736 [running]:
github.com/grafana/metrictank/api.doRecover(0xc5c88d1e48)
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/api/dataprocessor.go:29 +0x256
panic(0xbdd9a0, 0x115b350)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
github.com/grafana/metrictank/mdata.(*AggMetric).Get(0x0, 0x5a6cbee65a4531e6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/mdata/aggmetric.go:177 +0xb4
github.com/grafana/metrictank/mdata.(*AggMetric).GetAggregated(0xc48b9146e0, 0x2, 0x5a4531e600000e10, 0x5a6cbee6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/mdata/aggmetric.go:158 +0xea
github.com/grafana/metrictank/api.(*Server).getSeriesAggMetrics(0xc420782000, 0xc4e86c0550, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/api/dataprocessor.go:483 +0x1c1
github.com/grafana/metrictank/api.(*Server).getSeries(0xc420782000, 0xc4e86c0550, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10, ...)
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/api/dataprocessor.go:416 +0x7b
github.com/grafana/metrictank/api.(*Server).getSeriesFixed(0xc420782000, 0x1129400, 0xc8671ef980, 0xc5c4065c50, 0x22, 0xc7250dae60, 0x91, 0xc4ad331560, 0x85, 0x5a6cbee65a4531e6, ...)
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/api/dataprocessor.go:401 +0x132
github.com/grafana/metrictank/api.(*Server).getTarget(0xc420782000, 0x1129400, 0xc8671ef980, 0xc5c4065c50, 0x22, 0xc7250dae60, 0x91, 0xc4ad331560, 0x85, 0x5a6cbee65a4531e6, ...)
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/api/dataprocessor.go:340 +0x717
github.com/grafana/metrictank/api.(*Server).getTargetsLocal.func1(0x1129340, 0xc5e567aa00, 0xc420782000, 0xc5a7d39520, 0xc4ab8d8600, 0xc6bfe65880, 0xc448a6e660, 0xc5c4065c50, 0x22, 0xc7250dae60, ...)
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/api/dataprocessor.go:274 +0x162
created by github.com/grafana/metrictank/api.(*Server).getTargetsLocal
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/api/dataprocessor.go:270 +0x2bd
```

**Comment by shanson7** [comment]
This was a build from WIP branch
`2018/01/27 18:03:20 [I] Metrictank starting. Built from 0.7.4-681-g699e0fb - Go version go1.9.2`

**Comment by shanson7** [comment]
What makes this one particularly heinous is that it would crash every peer that had a timeseries matching the request. That means for a query with a lot of timeseries, it could take out an entire set of read instances. And if the user tried again...
