### ISSUE TITLE
Handle malformed messages consumed from Kafka

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#853]
Currently, when MT ingests malformed messages from Kafka, it can crash badly. It would be good to have an option that makes MT drop those messages but increase a counter that we can alert on. Then, if we get into a situation where for whatever reason malformed messages ended up in Kafka, we'll need to react fast and either kill TSDB or fix the reason for the malformed messages. 
The reasoning why this makes sense is because if a message is malformed then we will most likely not be able to recover the data out of it, so there is no point in trying to keep it. The most important thing in that situation should be that we get alerted as soon as possible to fix the reason why there were malformed messages in the first place.

Example of what currently happens:
```
2018/02/20 18:54:21 [kafkamdm.go:352 handleMsg()] [E] kafka-mdm decode error, skipping message. msgp: too few bytes left to read object
2018/02/20 18:54:21 [kafkamdm.go:352 handleMsg()] [E] kafka-mdm decode error, skipping message. msgp: too few bytes left to read object
2018/02/20 18:54:21 [kafkamdm.go:352 handleMsg()] [E] kafka-mdm decode error, skipping message. msgp: too few bytes left to read object
2018/02/20 18:54:21 [kafkamdm.go:352 handleMsg()] [E] kafka-mdm decode error, skipping message. msgp: too few bytes left to read object
2018/02/20 18:54:21 [kafkamdm.go:352 handleMsg()] [E] kafka-mdm decode error, skipping message. msgp: attempted to decode type "map" with method for "str"
2018/02/20 18:54:21 [kafkamdm.go:352 handleMsg()] [E] kafka-mdm decode error, skipping message. msgp: attempted to decode type "int" with method for "str"
2018/02/20 18:54:21 [kafkamdm.go:352 handleMsg()] [E] kafka-mdm decode error, skipping message. msgp: too few bytes left to read object
2018/02/20 18:54:21 [kafkamdm.go:352 handleMsg()] [E] kafka-mdm decode error, skipping message. msgp: too few bytes left to read object
2018/02/20 18:54:21 [kafkamdm.go:352 handleMsg()] [E] kafka-mdm decode error, skipping message. msgp: attempted to decode type "int" with method for "str"
2018/02/20 18:54:21 [kafkamdm.go:352 handleMsg()] [E] kafka-mdm decode error, skipping message. msgp: too few bytes left to read object
2018/02/20 18:54:21 [kafkamdm.go:352 handleMsg()] [E] kafka-mdm decode error, skipping message. msgp: too few bytes left to read object
panic: runtime error: index out of range

goroutine 1148 [running]:
github.com/grafana/metrictank/vendor/github.com/tinylib/msgp/msgp.UnsafeString(...)
       /go/src/github.com/grafana/metrictank/vendor/github.com/tinylib/msgp/msgp/unsafe.go:27
github.com/grafana/metrictank/vendor/gopkg.in/raintank/schema%2ev1.(*MetricData).UnmarshalMsg(0xc4519ae750, 0xc4a803664d, 0x159, 0x376, 0x1, 0xc47e69db90, 0x43c4ff, 0xc47e69dba0, 0xae6b2b)
       /go/src/github.com/grafana/metrictank/vendor/gopkg.in/raintank/schema.v1/metric_gen.go:254 +0x106c
github.com/grafana/metrictank/input/kafkamdm.(*KafkaMdm).handleMsg(0xc42078c9c0, 0xc4a8036613, 0x193, 0x3b0, 0xffffffff0000001e)
       /go/src/github.com/grafana/metrictank/input/kafkamdm/kafkamdm.go:349 +0x68
github.com/grafana/metrictank/input/kafkamdm.(*KafkaMdm).consumePartition(0xc42078c9c0, 0xc420014e87, 0xd, 0xc40000001e, 0xfffffffffffffffe)
       /go/src/github.com/grafana/metrictank/input/kafkamdm/kafkamdm.go:316 +0x61b
created by github.com/grafana/metrictank/input/kafkamdm.(*KafkaMdm).Start
       /go/src/github.com/grafana/metrictank/input/kafkamdm/kafkamdm.go:221 +0x10b
```

**Comment by Dieterbe** [comment]
it looks like this panic originates out of the msgp library.
note that when MT gets an error back from the `md.UnmarshalMsg` call it does log an error and increment a metric. (decode_err). we alert on invalid and known data, and i added this decode_err metric to our alert as well.
I agree we should log a bit more info, and update our msgp library, which might have this problem fixed.
